import React, { useState } from 'react';
import {
  StyleSheet,
  Text,
  View,
  ScrollView,
  Pressable,
  Platform,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons, Feather } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Haptics from 'expo-haptics';
import Colors from '@/constants/colors';
import { useMatches } from '@/context/MatchContext';

function generateCSV(matches: any[]): string {
  const watermark = 'Generated by KhoKho Score App';
  let csv = `${watermark}\n\n`;
  csv += 'Match ID,Date,Venue,Team A,Team A Score,Team B,Team B Score,Status,Auto-filled Fields\n';

  for (const m of matches) {
    const autoFilled = m.autoFilledFields.length > 0 ? m.autoFilledFields.join('; ') : 'None';
    csv += `"${m.id}","${m.date}","${m.venue}","${m.teamA.name}",${m.teamA.totalScore},"${m.teamB.name}",${m.teamB.totalScore},"${m.status}","${autoFilled}"\n`;
  }

  csv += `\n--- Player Details ---\n`;
  csv += 'Match Date,Team,Player Name,Player Score\n';

  for (const m of matches) {
    for (const p of m.teamA.players) {
      csv += `"${m.date}","${m.teamA.name}","${p.name}",${p.score}\n`;
    }
    for (const p of m.teamB.players) {
      csv += `"${m.date}","${m.teamB.name}","${p.name}",${p.score}\n`;
    }
  }

  return csv;
}

export default function ExportScreen() {
  const insets = useSafeAreaInsets();
  const webTopInset = Platform.OS === 'web' ? 67 : 0;
  const { matches, stats } = useMatches();
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async (type: 'all' | 'confirmed' | 'drafts') => {
    let data = matches;
    if (type === 'confirmed') data = matches.filter(m => m.status === 'confirmed');
    if (type === 'drafts') data = matches.filter(m => m.status === 'draft');

    if (data.length === 0) {
      Alert.alert('No Data', 'There are no matches to export for this filter.');
      return;
    }

    setIsExporting(true);
    if (Platform.OS !== 'web') Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

    try {
      const csv = generateCSV(data);
      const fileName = `khokho_scores_${type}_${Date.now()}.csv`;

      if (Platform.OS === 'web') {
        const blob = new Blob([csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = fileName;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        const fileUri = FileSystem.documentDirectory + fileName;
        await FileSystem.writeAsStringAsync(fileUri, csv, {
          encoding: FileSystem.EncodingType.UTF8,
        });
        const isAvailable = await Sharing.isAvailableAsync();
        if (isAvailable) {
          await Sharing.shareAsync(fileUri, {
            mimeType: 'text/csv',
            dialogTitle: 'Export Match Data',
          });
        } else {
          Alert.alert('Export Complete', `File saved as ${fileName}`);
        }
      }

      if (Platform.OS !== 'web') Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (err) {
      Alert.alert('Export Failed', 'An error occurred while exporting data.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <LinearGradient
      colors={[Colors.light.backgroundGradientStart, Colors.light.backgroundGradientEnd]}
      style={styles.container}
    >
      <ScrollView
        contentContainerStyle={[
          styles.scrollContent,
          { paddingTop: insets.top + webTopInset + 16, paddingBottom: 100 },
        ]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.title}>Export Data</Text>
        <Text style={styles.subtitle}>Share your match records</Text>

        <View style={styles.summaryCard}>
          <View style={styles.summaryRow}>
            <View style={styles.summaryItem}>
              <Text style={styles.summaryValue}>{stats.totalMatches}</Text>
              <Text style={styles.summaryLabel}>Total</Text>
            </View>
            <View style={styles.summaryDivider} />
            <View style={styles.summaryItem}>
              <Text style={styles.summaryValue}>{stats.confirmedMatches}</Text>
              <Text style={styles.summaryLabel}>Confirmed</Text>
            </View>
            <View style={styles.summaryDivider} />
            <View style={styles.summaryItem}>
              <Text style={styles.summaryValue}>{stats.draftMatches}</Text>
              <Text style={styles.summaryLabel}>Drafts</Text>
            </View>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Export Options</Text>

        <Pressable
          style={({ pressed }) => [styles.exportCard, pressed && { opacity: 0.92 }]}
          onPress={() => handleExport('all')}
          disabled={isExporting}
        >
          <View style={[styles.exportIcon, { backgroundColor: Colors.light.primary + '15' }]}>
            <Ionicons name="download-outline" size={24} color={Colors.light.primary} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.exportTitle}>Export All Matches</Text>
            <Text style={styles.exportDesc}>Download all {stats.totalMatches} matches as CSV</Text>
          </View>
          {isExporting ? (
            <ActivityIndicator color={Colors.light.primary} />
          ) : (
            <Feather name="chevron-right" size={20} color={Colors.light.textTertiary} />
          )}
        </Pressable>

        <Pressable
          style={({ pressed }) => [styles.exportCard, pressed && { opacity: 0.92 }]}
          onPress={() => handleExport('confirmed')}
          disabled={isExporting}
        >
          <View style={[styles.exportIcon, { backgroundColor: Colors.light.positive + '15' }]}>
            <Ionicons name="checkmark-circle-outline" size={24} color={Colors.light.positive} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.exportTitle}>Confirmed Only</Text>
            <Text style={styles.exportDesc}>Export {stats.confirmedMatches} confirmed matches</Text>
          </View>
          <Feather name="chevron-right" size={20} color={Colors.light.textTertiary} />
        </Pressable>

        <Pressable
          style={({ pressed }) => [styles.exportCard, pressed && { opacity: 0.92 }]}
          onPress={() => handleExport('drafts')}
          disabled={isExporting}
        >
          <View style={[styles.exportIcon, { backgroundColor: Colors.light.accent + '20' }]}>
            <Ionicons name="create-outline" size={24} color={Colors.light.accentDark} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.exportTitle}>Drafts Only</Text>
            <Text style={styles.exportDesc}>Export {stats.draftMatches} draft matches</Text>
          </View>
          <Feather name="chevron-right" size={20} color={Colors.light.textTertiary} />
        </Pressable>

        <View style={styles.infoCard}>
          <Ionicons name="information-circle-outline" size={18} color={Colors.light.primary} />
          <View style={{ flex: 1 }}>
            <Text style={styles.infoTitle}>About Exports</Text>
            <Text style={styles.infoText}>
              Exported CSV files include a watermark with the app name. All auto-filled fields are clearly flagged. Files can be opened in Excel, Google Sheets, or any spreadsheet application.
            </Text>
          </View>
        </View>
      </ScrollView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { paddingHorizontal: 20 },
  title: {
    fontSize: 28,
    fontFamily: 'Nunito_700Bold',
    color: Colors.light.text,
  },
  subtitle: {
    fontSize: 14,
    fontFamily: 'Nunito_400Regular',
    color: Colors.light.textSecondary,
    marginTop: 2,
    marginBottom: 24,
  },
  summaryCard: {
    backgroundColor: Colors.light.card,
    borderRadius: 22,
    padding: 20,
    marginBottom: 24,
    shadowColor: Colors.light.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
  },
  summaryDivider: {
    width: 1,
    height: 36,
    backgroundColor: Colors.light.border,
  },
  summaryValue: {
    fontSize: 24,
    fontFamily: 'Nunito_700Bold',
    color: Colors.light.text,
  },
  summaryLabel: {
    fontSize: 12,
    fontFamily: 'Nunito_500Medium',
    color: Colors.light.textSecondary,
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: 'Nunito_700Bold',
    color: Colors.light.text,
    marginBottom: 14,
  },
  exportCard: {
    backgroundColor: Colors.light.card,
    borderRadius: 20,
    padding: 18,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: Colors.light.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  exportIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exportTitle: {
    fontSize: 15,
    fontFamily: 'Nunito_600SemiBold',
    color: Colors.light.text,
  },
  exportDesc: {
    fontSize: 12,
    fontFamily: 'Nunito_400Regular',
    color: Colors.light.textSecondary,
    marginTop: 2,
  },
  infoCard: {
    backgroundColor: Colors.light.primaryLight,
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  infoTitle: {
    fontSize: 13,
    fontFamily: 'Nunito_600SemiBold',
    color: Colors.light.text,
  },
  infoText: {
    fontSize: 12,
    fontFamily: 'Nunito_400Regular',
    color: Colors.light.textSecondary,
    marginTop: 2,
    lineHeight: 18,
  },
});
